### PR TITLE
chore: wrap pattern in definition

### PR DESCRIPTION
**Pull request by ilevyor**

### CODE REVIEW

**Review by seren5240 — APPROVED** [review]

**Comment by seren5240** [comment]
Tests are failing.

**Comment by ilevyor** [comment]
> Tests are failing.

Yeah seems CI is running (just a guess really unsure) javascript tests, with language set to python. changes I made pass locally, and work in the pattern studio, most recent commit reverts everything so the diff is nothing, and ci still fails with:
"pattern definition not found: program. Try running grit init." even though "program" isn't found in the repo. Error message feels like it could be due to auto-wrap, but that doesn't explain why it works locally, and on the pattern studio.

**Comment by morgante** [comment]
It looks like there's probably a bug in `grit patterns test` that doesn't detect the right language? I'm very confused why it wouldn't appear locally for you though.

This is definitely not running JavaScript tests though. You can see that from this message:
> Found 2 testable patterns out of 2 local patterns. To test a pattern, make sure it is defined in .grit/grit.yaml or a .md file in your .grit/patterns directory and has samples.
> Error: invalid field `import` for node `import_statement`, valid fields are: name

**Comment by ilevyor** [comment]
> It looks like there's probably a bug in `grit patterns test` that doesn't detect the right language? I'm very confused why it wouldn't appear locally for you though.
> 
> This is definitely not running JavaScript tests though. You can see that from this message:
> 
> > Found 2 testable patterns out of 2 local patterns. To test a pattern, make sure it is defined in .grit/grit.yaml or a .md file in your .grit/patterns directory and has samples.
> > Error: invalid field `import` for node `import_statement`, valid fields are: name

Right more like it feels like we are including js dependencies

**Comment by seren5240** [comment]
> > It looks like there's probably a bug in `grit patterns test` that doesn't detect the right language? I'm very confused why it wouldn't appear locally for you though.
> > This is definitely not running JavaScript tests though. You can see that from this message:
> > > Found 2 testable patterns out of 2 local patterns. To test a pattern, make sure it is defined in .grit/grit.yaml or a .md file in your .grit/patterns directory and has samples.
> > > Error: invalid field `import` for node `import_statement`, valid fields are: name
> 
> Right more like it feels like we are including js dependencies

It probably is. We have no logic at all to filter grit files at this point. We just send all of them, as we've done from the start for marzano.

**Comment by seren5240** [comment]
https://github.com/getgrit/rewriter/issues/6566

**Pull request merged**
